### ISSUE TITLE
EPP works with one model but not when there are multiple models deployed in the cluster

### ISSUE THREAD

**Issue by jgchn** [llm-d/llm-d-inference-scheduler#158]
I have a set up in an OpenShift cluster for one model, similar to llm-d-deployer [sample-application](https://github.com/llm-d/llm-d-deployer/tree/main/charts/llm-d/templates/sample-application) set up. The only difference is HTTPRoute configuration, where in addition to a PathPrefix match, I am adding a header match. For example,

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  generation: 1
  name: granite-base-model-http-route
  namespace: e2e-solution
  ownerReferences:
  - apiVersion: llm-d.ai/v1alpha1
    kind: ModelService
    name: granite-base-model
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: inference-gateway
  rules:
  - backendRefs:
    - filters:
      - requestHeaderModifier:
          add:
          - name: x-model-name
            value: ibm-granite/granite-3.3-2b-base
        type: RequestHeaderModifier
      group: inference.networking.x-k8s.io
      kind: InferencePool
      name: granite-base-model-inference-pool
      port: 8000
      weight: 1
    matches:
    - headers:
      - name: x-model-name
        type: Exact
        value: ibm-granite/granite-3.3-2b-base
      path:
        type: PathPrefix
        value: /
```

When I send a curl request with `x-model-name: ibm-granite/granite-3.3-2b-base` as a header, I get a response as expected. Without the header, I get a 404. This works as expected.

However, using the same set up, I added deployments for another model. In particular, the cluster now contains:

- One inference gateway 
- Two HTTPRoutes linking to different InferencePools with different matches for the `x-model-name` header
- Two models with their own InferencePool and InferenceModel. The InferencePool and InferenceModel have selector labels that match
- Two EPPs associated with the model. The `--poolName` and `--poolNamespace` are set for both. The image I tested with are `0.0.3` and `v0.1.0` (latest)
- The models have their decode and prefill deployments, similar to the deployer set up. Set up is the same for both models

Ideally, I should be able to send a curl request with different headers, and get a response for each corresponding model. However, when I send the same request to the inference gateway, I now get a 404. I can confirm that the Gateway is forwarding the request to the EPP as I can see in the logs. The logs below show that the EPP gets a 200 response when there's one model in the cluster (second stanza), but gets a 404 response when there are two models (second stanza). This is the EPP log using the `v0.1.0` image.

```
{"level":"info","ts":"2025-05-29T19:20:02Z","logger":"setup","caller":"epp/main.go:146","msg":"Flags processed","flags":{"DestinationEndpointHintMetadataNamespace":"envoy.lb","certPath":"","destinationEndpointHintKey":"x-gateway-destination-endpoint","grpcHealthPort":9003,"grpcPort":9002,"kubeconfig":"","kvCacheUsagePercentageMetric":"vllm:gpu_cache_usage_perc","loraInfoMetric":"vllm:lora_requests_info","metricsPort":9090,"poolName":"granite-base-model-inference-pool","poolNamespace":"e2e-solution","refreshMetricsInterval":50000000,"refreshPrometheusMetricsInterval":5000000000,"secureServing":true,"totalQueuedRequestsMetric":"vllm:num_requests_waiting","v":6,"zap-devel":true,"zap-encoder":{},"zap-log-level":{},"zap-stacktrace-level":{},"zap-time-encoding":{}}}
...

{"level":"Level(-5)","ts":"2025-05-29T19:21:15Z","caller":"handlers/server.go:129","msg":"Processing"}
{"level":"Level(-5)","ts":"2025-05-29T19:21:15Z","caller":"handlers/server.go:322","msg":"checking","x-request-id":"0b4bd04a-320c-46d3-aab2-3c17588e8b0a","request state":0}
{"level":"Level(-5)","ts":"2025-05-29T19:21:15Z","caller":"handlers/server.go:189","msg":"Incoming body chunk","x-request-id":"0b4bd04a-320c-46d3-aab2-3c17588e8b0a","EoS":false}
{"level":"Level(-5)","ts":"2025-05-29T19:21:15Z","caller":"handlers/server.go:322","msg":"checking","x-request-id":"0b4bd04a-320c-46d3-aab2-3c17588e8b0a","request state":0}
{"level":"Level(-5)","ts":"2025-05-29T19:21:15Z","caller":"handlers/server.go:189","msg":"Incoming body chunk","x-request-id":"0b4bd04a-320c-46d3-aab2-3c17588e8b0a","EoS":true}
{"level":"Level(-5)","ts":"2025-05-29T19:21:15Z","caller":"handlers/server.go:195","msg":"decoding","x-request-id":"0b4bd04a-320c-46d3-aab2-3c17588e8b0a"}
...

{"level":"Level(-5)","ts":"2025-05-29T19:22:24Z","caller":"handlers/server.go:129","msg":"Processing"}
{"level":"Level(-5)","ts":"2025-05-29T19:22:24Z","caller":"handlers/server.go:231","msg":"header","key":":status","value":"404"}
{"level":"Level(-4)","ts":"2025-05-29T19:22:24Z","caller":"requestcontrol/director.go:150","msg":"LLM response assembled","response":{"RequestId":"","Headers":{":status":"404"},"Body":"","IsStreaming":false,"EndOfStream":false}}
{"level":"Level(-5)","ts":"2025-05-29T19:22:24Z","caller":"handlers/server.go:322","msg":"checking","request state":4}
```

If you have access to the [platform-opt cluster](https://console-openshift-console.apps.fmaas-platform-eval.fmaas.res.ibm.com/k8s/ns/e2e-solution/core~v1~Pod), you can review the two-model set up. Try the following:

```
oc login <your-login-command>
oc project e2e-solution
kubectl port-forward svc/inference-gateway 8000:80
curl http://localhost:8000/v1/completions -vvv \
    -H "Content-Type: application/json" \
    -H "x-model-name: ibm-granite/granite-3.3-2b-base" \
    -d '{
    "model": "ibm-granite/granite-3.3-2b-base",
    "prompt": "Hello, "
}' 
```
--> this returns a 404

Now, you can delete the HTTPRoute, InferencePool, and InfereceModel associated with this model by 

```
oc delete msvc granite-base-model
```

And try another request, which returned a response. 

```
curl http://localhost:8000/v1/completions -vvv \
>     -H "Content-Type: application/json" \
>     -H "x-model-name: facebook/opt-125m" \
>     -d '{
>     "model": "facebook/opt-125m",
>     "prompt": "Hello, "
> }' 
* Host localhost:8000 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8000...
* Connected to localhost (::1) port 8000
> POST /v1/completions HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/8.7.1
> Accept: */*
> Content-Type: application/json
> x-model-name: facebook/opt-125m
> Content-Length: 61
> 
* upload completely sent off: 61 bytes
< HTTP/1.1 200 OK
< x-envoy-upstream-service-time: 120
< x-went-into-resp-headers: true
< content-type: application/json
< date: Thu, 29 May 2025 19:43:13 GMT
< server: envoy
< transfer-encoding: chunked
< 
* Connection #0 to host localhost left intact
{"choices":[{"finish_reason":"length","index":0,"logprobs":null,"prompt_logprobs":null,"stop_reason":null,"text":" That is my dad. He was a wautdig with a shooting blade on"}],"created":1748547794,"id":"cmpl-2877e26e-f526-488e-a9ec-0d82dc27ee3b","kv_transfer_params":null,"model":"facebook/opt-125m","object":"text_completion","usage":{"completion_tokens":16,"prompt_tokens":4,"prompt_tokens_details":null,"total_tokens":20}}j
```

Also sharing the EPP pod manifest for the one of the models below. I also included the EPP configuration log message above. I can also dump the entire log. 

```
kind: Pod
apiVersion: v1
metadata:
  generateName: facebook-opt-125m-nixl-epp-58bbc8457d-
  name: facebook-opt-125m-nixl-epp-58bbc8457d-dxznn
  namespace: e2e-solution
  labels:
    llm-d.ai/epp: facebook-opt-125m-nixl-epp
spec:
  serviceAccountName: facebook-opt-125m-nixl-epp-sa
  containers:
    - resources: {}
      readinessProbe:
        grpc:
          port: 9003
          service: envoy.service.ext_proc.v3.ExternalProcessor
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      terminationMessagePath: /dev/termination-log
      name: epp
      livenessProbe:
        grpc:
          port: 9003
          service: envoy.service.ext_proc.v3.ExternalProcessor
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      env:
        - name: PD_ENABLED
          value: 'true'
        - name: PD_PROMPT_LEN_THRESHOLD
          value: '10'
      securityContext:
        capabilities:
          drop:
            - MKNOD
      ports:
        - containerPort: 9002
          protocol: TCP
        - containerPort: 9003
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
      imagePullPolicy: IfNotPresent
      image: 'ghcr.io/llm-d/llm-d-inference-scheduler:v0.1.0'
      args:
        - '-poolName'
        - facebook-opt-125m-nixl-inference-pool
        - '-poolNamespace'
        - e2e-solution
        - '-v'
        - '6'
        - '--zap-encoder'
        - json
        - '-grpcPort'
        - '9002'
        - '-grpcHealthPort'
        - '9003'
  serviceAccount: facebook-opt-125m-nixl-epp-sa
```

I don't understand why the EPP is getting a 404 response when there are two models but 200 when there's one model. Presumably, because the set up for one model works, the selector labels on InferecePool, InferenceModel, and PD pods should be correct. Below, I will share the InferencePool and InferenceModel specs as well. 

cc @sriumcp
